#!/usr/bin/env python3
"""Bootstrap the multiplayer and World Chat server from its base64 parts.

Parts are generated by tools/build-parts.py from server/server-source.py.
Every part is independently valid base64, so a damaged part raises here
instead of silently shifting the rest of the payload.
"""
from __future__ import annotations

import base64
import binascii
from pathlib import Path

root = Path(__file__).resolve().parent
parts_dir = root / "parts"
parts = sorted(parts_dir.glob("part*.b64"))

if not parts:
    raise SystemExit(f"No server parts found in {parts_dir}. Run: python3 tools/build-parts.py")

chunks: list[bytes] = []
for part in parts:
    encoded = "".join(part.read_text(encoding="ascii").split())
    try:
        chunks.append(base64.b64decode(encoded, validate=True))
    except (binascii.Error, ValueError) as exc:
        raise SystemExit(
            f"Server part {part.name} is corrupt ({exc}). Run: python3 tools/build-parts.py"
        ) from exc

source = b"".join(chunks).decode("utf-8")
exec(compile(source, str(root / "server-v4.3.0-runtime.py"), "exec"), globals(), globals())
